[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

# Required so tests use correct deployment
always_use_create_2_factory=true

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
forge-std = "1.9.4"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
