[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
optimizer = true

[fmt]
multiline_func_header = "params_first_multi"

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
forge-std = "1.9.4"


[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
katana_mainnet = ""
katana_testnet = ""

[etherscan]
katana_mainnet = { key = "${ETHERSCAN_API_KEY}" }
katana_testnet = { key = "${ETHERSCAN_API_KEY}" }